export const PORT = process.env.PORT || 8200
export const DB_HOST = process.env.DB_HOST || 'localhost'
export const DB_NAME = process.env.DB_NAME || 'hamwich'
export const DB_PORT = process.env.DB_PORT || 5432
export const DB_USER = process.env.DB_USER || 'development'
export const DB_PASS = process.env.DB_PASS || 'development'
export const AWS_KEY = process.env.AWS_KEY
export const AWS_SECRET = process.env.AWS_SECRET
export const AWS_BUCKET = process.env.AWS_BUCKET
